### ISSUE TITLE
Flux Field Un-registers SSP

### ISSUE THREAD

**Issue by hazerofdoom** [joekaiser/QuantumFlux#10]
Mod Pack: FTB Infinity 2.1.6 (I think -- it's the newest version anyway).
Type of world: Single Player
Issue:

When logging out of the game / closing the game, upon re-entering the game the field (machines) aren't registered to you anymore. This is with the same account.
Breaking the Quantum RF Exciters on their own and re-placing does not fix this issue.
This is probably because the Entangler is still not registered to you, so the power you pump into it is not going into your 'flux field' therefore your new RF exciters are not receiving the energy.
When you break the Entangler and replace it, as well as ALL of the exciters - then it starts to work again.

Steps to recreate:

Pump power into Entangler.
Take power from Exciter.
Do things to make sure it's working.
Exit FTB.
Re Open FTB.

You will then see that (after draining your machines of power) that they're not getting the power that's being pumped into your entangler.

**Comment by hazerofdoom** [comment]
https://www.youtube.com/watch?v=qcgZpAaOl7Y

Made a video showing it in a creative world.
Mind the badness, I don't make videos normally.

I have 2 extra mods though for note:

Magical Crops
Torcherino

**Comment by joekaiser** [comment]
Fixed in 1.0.1
