### ISSUE TITLE
Imaginary Time Block ignoring config

### ISSUE THREAD

**Issue by Shirkit** [joekaiser/QuantumFlux#103]
Hello,

The configuration for the Tick Rate Increase is currently being ignored. I do not know if it's a bug or not, you can check that that information is not currently being used at all here: https://github.com/joekaiser/QuantumFlux/blob/e345b0ca9e0cba2a234d1d3c4887fd4546661c12/src/main/java/jotato/quantumflux/machines/imaginarytime/TileImaginaryTime.java#L50

**Comment by joekaiser** [comment]
That is by design. I need to do cleanup on the config. I'll get to that next
