### ISSUE TITLE
Battlesuit Blackout

### ISSUE THREAD

**Issue by bert1085** [joekaiser/QuantumFlux#104]
I upgraded my battlesuit helmet with vision and now I have a permanent black out every time I put it on. I'm playing the Galactic Science modpack with MC 1.7.10

**Comment by joekaiser** [comment]
if you take a night vision potion, does the same thing happen?

**Comment by joekaiser** [comment]
any word on this, or is it OK to close it? I have tried on 3 computers and can't reproduce it

**Comment by bert1085** [comment]
Ok, thanks for looking into it.

Sent using OWA for iPhone
________________________________

**Comment by joekaiser** [comment]
no-repro. Will re-open if this turns out to be a bug
