### ISSUE TITLE
matter transporter can only transport decorative blocks

### ISSUE THREAD

**Issue by Hypsellis** [joekaiser/QuantumFlux#105]
I don't know if it's bug but the matter transporter seems unable to transport active blocks like chest, crafting table, furnace, anvil, enchantment table... or other active blocks of other mods. I can only transport decorative blocks.

**Comment by joekaiser** [comment]
You have to hold shift while right clicking

**Comment by Hypsellis** [comment]
Hm ok thanks for the information, and sorry for the bothering. ;)
