### ISSUE TITLE
Less verbose Logging

### ISSUE THREAD

**Issue by MrAmericanMike** [joekaiser/QuantumFlux#106]
Would it be possible to have a config to turn off the outputs to the console that show the blocks registering.

Example: [12:23:30] [Client thread/INFO]: [@QuantumFlux]     Registering model for industrialDiamond

Not a big deal if it isn't possible, but it would be nice to have.

**Comment by joekaiser** [comment]
Why though? It is a one time log

**Comment by MrAmericanMike** [comment]
I like clean Logs when packs are starting. It's just that, that's why I said, if it's not possible, it's ok. I just think it isn't important to show in log if X item/block or whatever was registered. Maybe it does makes sense on a Dev environment when you checking new stuff, or things like that, but for the final player, no really needed on the log.

**Comment by joekaiser** [comment]
This will be changed to a devlog message in future versions
