### ISSUE TITLE
[Suggestion] Imaginary Time Block Power Requirement

### ISSUE THREAD

**Issue by condensedapple** [joekaiser/QuantumFlux#108]
Can you increase the maximum possible amount of RF/t required to run the ITB? This would be awesome, as I (personally) consider them balanced if they use 50kRF/t or more.
This sould not be too difficult, changing these two lines should do the thing: https://github.com/joekaiser/QuantumFlux/blob/1.3.2/src/main/java/jotato/quantumflux/ConfigMan.java#L80 and 81 (I use QuantumFlux for 1.7.10)

**Comment by joekaiser** [comment]
No changes will be made for 1.7.10, sorry

I have tweaked the itb for 1.10, and will keep changing it until.I find a good balance.

**Comment by condensedapple** [comment]
am I allowed to change this for me personally (own gradle build/no redistributing)?

**Comment by joekaiser** [comment]
Go fo it :)


________________________________

**Comment by condensedapple** [comment]
thanks a lot ;)
