### ISSUE TITLE
Changing the recepie of the Quibit Clusters

### ISSUE THREAD

**Issue by Greg9711** [joekaiser/QuantumFlux#110]
The cost to make a Quibit Cluster level 5 is way to high, so maybe you could change the recipe so the level 5 cluster isnt sooooooooooooo dang expensive.

**Comment by joekaiser** [comment]
Expensive is relative. The idea isn't to jump right to the level 5, but to work tour way up as you need it. I won't be changing the recipe. There are plenty of ways available to change it in a modpwck. If you need to, try mine tweaker

**Comment by Greg9711** [comment]
I´m not sure if you can still read this after this issue is closed but the Level 5 one i think costs alout 6 stacks of diamonds, 18 Stacks of gold etc... and for changing the recipe myself, i´m not a fan of changing the game in that way because it feels wrong if there is something that the mod author didnt intend.
