### ISSUE TITLE
Titanium ingot unlocalized name duplicate

### ISSUE THREAD

**Issue by Wyrrrd** [joekaiser/QuantumFlux#111]
Hi, uncommon request for 1.7.10 here:

I am trying to change the name and behaviour of Galacticraft's Titanium Ingot with Minetweaker.
Strangely the QuantumFlux Ingot responds to every name change I apply to the GC ingot, while the GC ingot always takes the ore dictionary entry from the QF ingot.

Critical mod setup:
  - Galacticraft 3.0.12
  - QuantumFlux 1.3.4
  - Minetweaker 3.0.10B

I am not sure where this is coming from (my suggestion is, they have the same unlocalized name), so I am filing issues on GC and Minetweaker, too.

[Galacticraft Issue](https://github.com/micdoodle8/Galacticraft/issues/2270)
[Minetweaker Issue](https://github.com/stanhebben/MineTweaker3/issues/376)

Thanks in advance,
Wyrrrd

![unbenannt](https://cloud.githubusercontent.com/assets/11527443/18447132/a0a67846-7925-11e6-80cc-7dcea20c8675.png)

**Comment by joekaiser** [comment]
Why do you want them to be different? They are both titanium and ore-dict' to be the same.....

**Comment by Wyrrrd** [comment]
I'd like to change the GC ingot to be unique (it doesn't matter much in GC really) to force players to go to every planet.

**Comment by joekaiser** [comment]
Sorry, but there is nothing I am going to do about this. The 1.7.10 branch is locked (with an exception for critical bugs) Have you tried removing my version of Titanium from the ore dictionary using MT? That would be how I would approach the problem - not by renaming things

**Comment by Wyrrrd** [comment]
I am, actually, but somehow MT doesn't work like this...
(Of course renaming only won't work. This was just the goal.)

Thanks anyways :)
 I will try to find a workaround somehow.
