### ISSUE TITLE
Quantum Entropy Accelerator configs

### ISSUE THREAD

**Issue by xelrix** [joekaiser/QuantumFlux#113]
It seems like any items inserted will "burn" for just 1 tick regardless of the configs value.
Using quantumflux 2.0.8

**Comment by joekaiser** [comment]
I'll look into it. thanks

**Comment by joekaiser** [comment]
Yup, its a bug alright. It is an easy fix. I should be able to get it patched this weekend.

https://github.com/joekaiser/QuantumFlux/blob/1.9/src/main/java/jotato/quantumflux/machines/entropyaccelerator/TileEntropyAccelerator.java#L25
