### ISSUE TITLE
EntityItemGraphiteDust problem with sponge

### ISSUE THREAD

**Issue by KasperFranz** [joekaiser/QuantumFlux#119]
Submitting a bug report? Please fill out the form below the best you can.

*Version:*  1.10.2-2.0.9

*Mod pack:* any pack with QuantumFlux and Sponge on the server side

*Summary:*  When throwing the item (with Q) the item is tossed but since the event is cancelled it remain in your inventory (Sponge behavior) 

____

**What is happening** 
It "spawns" the item but it doesn't remove one from your inventory.

**How can I reproduce the problem?** 
Install spongeForge and your mod

**Comment by KasperFranz** [comment]
any update @joekaiser?

**Comment by joekaiser** [comment]
I'm not sure this is something I am going to fix soon. I see this as a problem with how sponge interacts with forge.

When you toss and item, I hook into the ItemTossEvent provided by forge. If the item in question is graphite dust, I modify the type if ItemEntity being generated and cancel the event so no one else can mess with it. As I understand it, this is the proper way to achieve what I want. If sponge is doing something on top of it, I would think it is on them to fix how the handle events.

This isn't to say I won't ever swing back around to this, but I just don't see it happening this month.

**Comment by KasperFranz** [comment]
But why is it that you need to modify it? 

as far as i read your code you are just remaking the item?  and not modificering the item

https://github.com/joekaiser/QuantumFlux/blob/d7c931ecf5f1415ce16e056dc70da1daf706fb21/src/main/java/jotato/quantumflux/registers/EventRegister.java#L77-L81

https://github.com/joekaiser/QuantumFlux/blob/d7c931ecf5f1415ce16e056dc70da1daf706fb21/src/main/java/jotato/quantumflux/items/EntityItemGraphiteDust.java#L30+L42

I am pretty sure that Sponge is gonna respond that the way you are handling the block is the problem and not their protection, I am also quite sure that this would also happen on a 1.7.10 with Cauldron etc.

**Comment by KasperFranz** [comment]
This got fixed by this commit:

https://github.com/SpongePowered/SpongeForge/commit/8230a5277a856ecb9d9c35fac5d350374d324e11

Sponge issue: https://github.com/SpongePowered/SpongeForge/issues/1048
