### ISSUE TITLE
Add options to disable oregen in config

### ISSUE THREAD

**Issue by ajthemacboy** [joekaiser/QuantumFlux#124]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* quantumflux-1.10.2-2.0.11

*Mod pack:* Custom pack

*Summary:* Please an an option to disable ores in the config. In #58 you added an option to disable Titanium in the config, but I no longer see this option, and I'm looking for a way to disable "Industrial Grade Graphite Ore."

____

**What is happening** NA

**How can I reproduce the problem?** NA

**Comment by joekaiser** [comment]
I don't plan on adding this change. I allowed titanium to be disabled because it was part of the OreDict and it could mess with other mods. The "Industrial Grade Graphite Ore." is used to make the diamonds and disabling it would break recipes
