### ISSUE TITLE
Any documentation on telepads?

### ISSUE THREAD

**Issue by DarkyAlan** [joekaiser/QuantumFlux#127]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* 
1.10.2-3.3.2
*Mod pack:* 
Invasion 1.0.7
*Summary:*
I can't seem to figure out how to use them at all.
____

**What is happening** 
I've used the Telepad Linking Card to connect two telepads in the same room to test them, but I don't see any interface other than the Linking Card confirming that the pads are linked. Can't seem to find any block that would be relevant to the telepad? No input for RF or any power source? 

So yeah, I'm just stumped, can't even find mention of the telepad in the wiki.

**Comment by joekaiser** [comment]
once they are linked, it will teleport you when given a redstone signal. Slap a lever on it :)

**Comment by DarkyAlan** [comment]
I'm dumb, didn't even consider applying a redstone signal, so use to things taking RF or some other sort of energy or having an interface.

Any possibility of it working across dimensions in the future? Was kind of sad when my options were either your mod or EnderIO on the modpack only to realize yours doesn't do cross dimension and EnderIO teleporters are SO power hungry.

**Comment by joekaiser** [comment]
Not at this time. They are simple and cheap because they don't work cross-dimension.
