### ISSUE TITLE
RF Entangler can not receive energy wirelessly

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#3]
Currently the RF Entangler has no support to receive energy wirelessly. It would be nice if the RF Exciter was able to have a mode to send RF back into the network for the Entangler to consume.

**Comment by joekaiser** [comment]
After thinking about it, I won't be changing this

**Comment by walkerjonny** [comment]
What about making own components for this, maybe an RF Feeder and an RF Receiver as an extension to the RF Entangler

**Comment by joekaiser** [comment]
What would they do?  This project is open sourced, so you can modify anything and submit a pull request for it. I can't promise every change is going to be accepted though, and I would feel bad if you waisted your time. Probably best to create a new issue describing what you want to do first.
