### ISSUE TITLE
darkstone lamp kills rei`s map

### ISSUE THREAD

**Issue by fistidgious** [joekaiser/QuantumFlux#37]
hi just started to play with the lamps they are awsome but have noticed as soon as i place 1 it kills off rei`s minimap i get error 508, the second the block is placed and the minimap is gone.

i running 1.7.10-1.2.0 of quant flux ad the latest cofh core 1.7.10-3.0.3B2-294, which contains the latest cofh lib

i not get a crash report just the error on screen but i can recreate the crash and send any logs if required

**Comment by joekaiser** [comment]
Can you provide any more detail?

- What pack?
- What version of REI?
- Is it only the Lamp?
- Do you have a way of capturing video? (If not, don't worry about it)
- Please attach the log file so I can see if there is anything

**Comment by fistidgious** [comment]
srry its not a public pack just a bunch of mods i throw together as i found them tho they are all the latest 1.7.10 versions, and yes it is only the lamp that causes it. I have discovered that is i place the lamp underground or in a roofed area that it works perfectly, when it is placed in view of the sky thats when the crash happens, its as tho the map not knowing what to display the lamp as on it.

rei`s map 1.7.10-3.6 
![2015-07-11_09 04 09](https://cloud.githubusercontent.com/assets/13280443/8632976/e6db379c-27ab-11e5-92ea-301d58e76aa5.png)
![2015-07-11_09 04 22](https://cloud.githubusercontent.com/assets/13280443/8632977/eeb082ba-27ab-11e5-84cc-49c3d6b1b34d.png)

github wont let me attach log here i will try send it in a pm

**Comment by fistidgious** [comment]
Scratch the last lot i jus downloaded the 1.7.10-1.2.3 jar for quantum flux and it fixed the bug itself.

awsome work on the mod btw i a huge fan of it and practicalities
![2015-07-11_09 22 42](https://cloud.githubusercontent.com/assets/13280443/8633037/6e27a15c-27ae-11e5-84fa-f9ffc73e7683.png)

Thanx so much for the quick response
