### ISSUE TITLE
Quibit Cluster 5 has stats of Cluster 4

### ISSUE THREAD

**Issue by mercsniper** [joekaiser/QuantumFlux#39]
<img width="1920" alt="screen shot 2015-07-12 at 11 38 43 pm" src="https://cloud.githubusercontent.com/assets/2205993/8642248/5807222a-28ef-11e5-8727-0fa5cce75fcd.png">

**Comment by joekaiser** [comment]
Which Cluster are you using? I am in the process of refactoring some code, and as a result had to re-do the Clusters. 

Break the block and put it in a crafting grid. It should convert over to the new block

**Comment by mercsniper** [comment]
These were the new Quibit 5's, not the old 5's. 



—
