### ISSUE TITLE
Item Fabricator recipes in NEI not showing in multiplayer

### ISSUE THREAD

**Issue by FantasyTeddy** [joekaiser/QuantumFlux#44]
Hi Jotato

I tried out the newest version of QuantumFlux (1.3.0-b2) with some friends and we discovered, that only the host was able to view the item fabricator recipes (e.g. Mystic Quartz) in NEI.

I did some digging and tried to locate where things go wrong and [this](https://github.com/joekaiser/QuantumFlux/blob/master/src/main/java/jotato/quantumflux/QuantumFlux.java#L101) is what's not being called on a client joining a server if I'm not mistaken. Unfortunately I'm not too sure how to correct this, otherwise I would have tried creating a PR, but I think you know what to do =)

Best regards and keep up the good work
FantasyTeddy

**Comment by joekaiser** [comment]
I will look into it. I don't think that code is the problem. A person I very much trust suggested to do it that way.

**Comment by FantasyTeddy** [comment]
Great, it is working now :smiley:

**Comment by joekaiser** [comment]
Here is the latest build if you want to download it http://minecraft.curseforge.com/mc-mods/228609-quantumflux/files/2249984
