### ISSUE TITLE
Battlesuit Config for armor pieces

### ISSUE THREAD

**Issue by Gr12zly** [joekaiser/QuantumFlux#45]
This is actually a possible enhancement. What are your thoughts on possibly adding a key config to disable the battlesuit upgraded features. Like maybe hold down the key and a menu pops up to choose which ones to disable, because i don't always want the speed upgrade turned on and others may be good to have off. Like haste for example. Just a thought on that!

Thanks

**Comment by joekaiser** [comment]
I don't think I am ever going to implement this. Closing for now
