### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by catzs** [joekaiser/QuantumFlux#46]
Using Opis I found out that the reason my game was lagging so much were RF Exciters. Maybe you could improve efficiency. Look at Tesseract code, no lag at all(using Daybreaker, so can't use them).

**Comment by catzs** [comment]
Actually brings my TPS from 3 to 15 ):

**Comment by joekaiser** [comment]
I am going to need more than this to go by. I perf test using Opis and the exciters/entanglers barely register

**Comment by catzs** [comment]
![qf lag test all setup opis](https://cloud.githubusercontent.com/assets/12586946/8943919/6f5eabec-354b-11e5-86df-a858099130e7.png)

**Comment by catzs** [comment]
Quantum Flux Lag Test, All Setup, TPS
![qf lag test all setup tps](https://cloud.githubusercontent.com/assets/12586946/8943933/85bbab92-354b-11e5-9c55-6a7ae9ada7d1.png)

**Comment by catzs** [comment]
QF Lag Test, Mekanism Setup, Opis
![qf lag test mekanism setup opis](https://cloud.githubusercontent.com/assets/12586946/8943951/9c87619a-354b-11e5-94f9-768258195457.png)

**Comment by catzs** [comment]
QF Lag Test, Mekanism Setup, TPS
![qf lag test mekanism setup tps](https://cloud.githubusercontent.com/assets/12586946/8943962/ad1bb52e-354b-11e5-894d-cc958865e51e.png)

**Comment by catzs** [comment]
QF Lag Test, QF Setup, Opis
![qf lag test qf setup opis](https://cloud.githubusercontent.com/assets/12586946/8943972/bdbe1368-354b-11e5-816b-2726e70faf02.png)

**Comment by catzs** [comment]
QF Lag Test, QF Setup, TPS
![qf lag test qf setup tps](https://cloud.githubusercontent.com/assets/12586946/8943977/c62d316e-354b-11e5-8a94-3e1d75575798.png)

**Comment by catzs** [comment]
QF Setup means only the QF Machines are placed down
Mekanism Setup means only the Mekanism machines are placed down
All Setup means both Quantum Flux & Mekanism machines are placed down
The higher performance in 5&6 are explained by the fact that the exciters/ZPE's are not connected to anything, which won't happen in actuality.

**Comment by catzs** [comment]
Compared to many other mods, Quantum Flux is poorly optimized.

**Comment by catzs** [comment]
No offense

**Comment by joekaiser** [comment]
Which TPS image do you think is bad? From what I can see in ever one the overall rate is superb. Am I missing something

**Comment by joekaiser** [comment]
I don't see any TPS issues in the screenshots you posted. I also haven't been able to see any in local testing or in real world servers I have played on. I am going to close this, but if you can show me actual proof (included your setup) feel free to comment and I will re-open it
