### ISSUE TITLE
Two sets of Quibit Clusters in NEI

### ISSUE THREAD

**Issue by beewyka819** [joekaiser/QuantumFlux#47]
As the title states, in NEI there are two sets of the Quibit CLsuters showing up, one that displays the recipes and one that does not, just thought I'd point this minor bug out.

**Comment by joekaiser** [comment]
The clusters without a recipe are marked as deprecated. If you have any put them in a crafting grid to convert them over to the new one. In 1.3.0 the old ones will not show in NEI or the creative menu
