### ISSUE TITLE
Mod Causes Game Crash

### ISSUE THREAD

**Issue by rcistano** [joekaiser/QuantumFlux#50]
Game was working without a problem, put in the mod and upon entering the world my game crashed. (I figured out the problem to this)

Also, a remote or device to combine with the wireless to make it direct where the power goes and how much to provide would be good. This will prevent other people from putting an exciter on their machines and using my power.

**Comment by joekaiser** [comment]
1. Please attach logs. I can do nothing without them

2. People can't steal your power. Each Exciter/Entangler is locked to the player who placed it

**Comment by rcistano** [comment]
That's good to know that no one other than me can use my power.

**Comment by joekaiser** [comment]
Nag. We have enough pipes in the game :)

**Comment by joekaiser** [comment]
I mean "no" :)

**Comment by rcistano** [comment]
What I mean is that besides wireless RF . I am looking forward to the mod that you have been working on that will provide us with a storage multiblock
