### ISSUE TITLE
[1.3.0] Reported: Storehouse leaks items

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#51]
It was reported that the storehouse leaks items. Investigate, and see if the cause is real or not

**Comment by rcistano** [comment]
I have sat there with a few items in there and nothing has happened. I only spent about 5 minutes with it. not sure how the items leak out.

**Comment by joekaiser** [comment]
By "Leaks" i mean loses. I am looking into the cause and I wouldn't use it until I have fixed it

**Comment by joekaiser** [comment]
Fixed by 6569016
