### ISSUE TITLE
Quibit Clusters should push energy out

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#6]
Right now you need a pipe like the Energy Extraction pipe to get RF from the Clusters. They should auto push out so you can chain them together

**Comment by walkerjonny** [comment]
I double that. Most energy storage blocks from other mods at least can be configured somehow to auto push to defined output sides. I think a configuration option like on the TE Energy Cells would be nice.

**Comment by joekaiser** [comment]
Partially fixed in the next update. The Clusters will push out, just not to other Clusters. The reason is you can get a feedback loop where they push to each other. I will work on configuring sides later, but this should help for now

**Comment by joekaiser** [comment]
I am closing this issue and opening  a new one to properly track the desired change
