### ISSUE TITLE
Request for a Later-Game Quibit Cell

### ISSUE THREAD

**Issue by ShadowsVengeance** [joekaiser/QuantumFlux#62]
The Quibit Cell paired with the ZPE is one of the coolest ideas in modded minecraft. That being said, 100rf/t transfer on the quibit cell is a bit underwhelming. While it might be sufficient for most setups, it might be pretty cool if there was some way to upgrade that, however expensive that may be.

Keep up the awesome work! :D

**Comment by joekaiser** [comment]
I don't understand. The Quibit Cell is the item that stays in your inventory. It can charge any item in your inventory (armor/tools/etc) at 100 RF/tick *each*.

That means if you have a full set of armor, it will use a max of 400 rf/tick What are you using in your inventory that requires more power than that?

**Comment by ShadowsVengeance** [comment]
Yeah,  thinking back on it,  you are probably right; maybe I was just
thinking fir epic's sake.  Sorry for the empty issue.

**Comment by joekaiser** [comment]
Don't be sorry :) throwing ideas out is how things get better
