### ISSUE TITLE
Battlesuit

### ISSUE THREAD

**Issue by TertyTree** [joekaiser/QuantumFlux#63]
Possible enhancement. I am not if it's just me not being able to get it to work or if the battlesuit armor actually doesn't work with the Thermal Expansion capacitors. It would be amazing if it did.

**Comment by joekaiser** [comment]
What exactly is the problem? What are you trying to do with the capacitors and the battlesuite?

**Comment by TertyTree** [comment]
From what I understand the damage you receive is based on the amount of charge that the battlesuit armor holds but the only way to charge it on the go is with the quibit cell, however I find it extremely difficult to understand how the quibit cell works but I do understand how the resonant capacitor from Thermal Expansion works. It'd be nice if you could charge the battlesuit armor with the resonant flux capacitor in your inventory instead of being limited to only the quibit cell.

**Comment by joekaiser** [comment]
The battle suit does work the the capacitors, the problem you are having is that the Flux Capacitors only charge *held items*. That means unless the item is in your hand, it will not be charged.

The Quibit Cell isn't difficult. First you want to make an RF Entangler and push RF into it. Then make a Quibit Cell, sneak+rClick to activate it and it will charge anything in your inventory
