### ISSUE TITLE
(enhancement) Omega Farm

### ISSUE THREAD

**Issue by teamMK** [joekaiser/QuantumFlux#64]
Hey,

maybe a late game farming idea for this mod. The omega garden multiblock structure wich will grow your crops more efficient but use water and rf. the Count of plants that can grow inside depends on the structure size 3*3*X.

This is a pic of the omega garden in rl:
http://www.ecofriend.com/wp-content/uploads/2012/07/omega_2_lAwTC_69.jpg
https://a1-images.myspacecdn.com/images01/124/d223746de2f0e42eb6aa89a7beddc949/full.jpg

Additions/Upgrades/Crossmod Integration:

Autofarming Upgrade

Lamp of Growth Neon lights (replace the normal lights with some kind of thaumic green lamp of growth) or imaginary time Upgrades

Mana Injector ( machine can use mana for some placed agricarnation flowers)

Efficiency Upgrade (lower rf and water cost)

UV Lamp: better gain for each crop

Fertilizer Injector ( Additonal Resource Output [use some Bonemeal/Fertilizer])

**Comment by joekaiser** [comment]
This is a good idea, and I really appreciate the well thought out concept, but I don't really see it fitting in the the mod.
