### ISSUE TITLE
[1.3.0] Item Magnet + OpenBlocks /dev/null does not work together

### ISSUE THREAD

**Issue by hron84** [joekaiser/QuantumFlux#65]
When I use OpenBlocks /dev/null and an active Item Magnet, /dev/null does not take the configured itemstacks - without magnet, it works as expected. I do not know this is your side or OpenBlocks side, but I kindly ask to investigate this issue.

Affected versions:

 - QF: 1.2.3
 - OB: 1.4.3

ModPack: FTB Horizons II with disabled Redstonic mod.

Crossref: OpenMods/OpenBlocks#698

**Comment by boq** [comment]
Hi, OpenMods author here.

For context, [here is our code](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/item/ItemDevNull.java#L135): we are using `EntityItemPickupEvent` to catch picked items and then set stack size to 0.

Looking at [your code](https://github.com/joekaiser/QuantumFlux/blob/master/src/main/java/jotato/quantumflux/items/ItemMagnet.java) it seems that you create this event, but don't post it (`MinecraftForge.EVENT_BUS.post`), so we never have chance to handle it.

**Comment by hron84** [comment]
@boq thanks for your investigation, I really appreciate your help :smile:

**Comment by joekaiser** [comment]
Thanks. Will fix in 1.3.1

**Comment by hron84** [comment]
@joekaiser thanks for this really quick fix.

**Comment by joekaiser** [comment]
As a side note, it was refreshing to see a proper bug report :)
