### ISSUE TITLE
Exciter tiers

### ISSUE THREAD

**Issue by expl0s1ve** [joekaiser/QuantumFlux#66]
RF exciters are great but next to the TE tesseracts, they are a fart in the wind. Maybe you can add (possibly much more expensive) tiers of exciters (or exicter upgrades). Even with a stack of upgrades I can barely get to a little more than 6k RF/t, which is not enough for powering many machines.

**Comment by expl0s1ve** [comment]
NVM, saw the closed issue.

**Comment by joekaiser** [comment]
You can add up to 640 upgrades to an exciter.

**Comment by expl0s1ve** [comment]
The entagler has no limits right?

**Comment by joekaiser** [comment]
Right
