### ISSUE TITLE
Storehouse should not spill the entire inventory when broken

### ISSUE THREAD

**Issue by xelrix** [joekaiser/QuantumFlux#74]
Currently, when broken, it will spill out everything in it.
Pretty undesirable considering it can store 999 items, making it likely a chosen method of main item storage.
Portability could make this perfect. Unless of course, if you implemented a in-GUI crafting grids. That would make it even more perfect.

**Comment by joekaiser** [comment]
I don't think I want it to keep all items when broken. Maybe it should drop the "quantum disk" and that disk has inventory. 

You could then insert that disk into another storehouse to transfer the stuff over
