### ISSUE TITLE
[Bug] Orientation problem

### ISSUE THREAD

**Issue by xelrix** [joekaiser/QuantumFlux#76]
The blocks seem to have problem facing NORTH and WEST.
They'll face SOUTH whenever I tried to make them face NORTH or WEST.

No trouble making them face SOUTH and EAST though.

**Comment by joekaiser** [comment]
What blocks are you referring to?

**Comment by xelrix** [comment]
In my case, the RF Entangler and the Storehouse. I think this affect all QuantumFlux blocks that have a single face.

**Comment by joekaiser** [comment]
Yeah, I thought it was weird. I wasn't able to reproduce it either. I'm glad it is all sorted out for you!

**Comment by xelrix** [comment]
Just a tiny followup. This happens when i tried to place blocks when I'm not at the same level as the block I'm placing. For example, trying to place a Storehouse on an obsidian while I'm standing on a halfslab.
