### ISSUE TITLE
Crystallized Redstone and Redstone Ingots {mod conflict}

### ISSUE THREAD

**Issue by NullMagic** [joekaiser/QuantumFlux#79]
So I run a pretty big mod pack (it's called "Devour The World" for reference) and we've recently run into an issue. It appears that Quantum Flux and the Calculator mod have a compatibility issue when it comes to cooking redstone in a furnace, often it defaults to the Calculator version which gives you redstone ingots and only occasionally can you get Crystallized redstone.

Obviously both mods can't have their way in this instance, at least in regards to normal vanilla furnaces and most furnaces from other mods which replicate vanilla functionality, so I'd like to make a couple suggestions to help with this issue.

The first is some kind of powered furnace of your own, that way you can manually force it to provide crystallized redstone instead of the output of any other mod. Alternatively you could add a recipe to your item fabricator that uses Redstone and some other block to create crystallized redstone.

The second is only helpful to those who are using Buildcraft in their packs, as it registers a Crystallized Redstone of it's own which is registered in the ore dictionary as both "crystalRedstone" and "redstoneCrystal", if you were to also register your own as either of those it would then be interchangeable in recipes allowing the use of the buildcraft version in your recipes and yours in its.

I'm afraid I don't have many other suggestions worth listing, and I hope that something can be determined that will sidestep this issue as it would be regrettable to remove either mod from our pack.

Thank you for taking the time to consider this.

**Comment by joekaiser** [comment]
I will sync up with the ore dict for sure, but until then my suggestion would be to just use minetweaker and change the recipe of one of the other.

**Comment by joekaiser** [comment]
Oh, I should have a build up that uses the predict by Monday. So maybe it doesn't matter.

**Comment by joekaiser** [comment]
I decided to just remove the item and use redstone instead. My smelted version didn't really add any value and just added tedium to the mod. New version is on Curse
