### ISSUE TITLE
Recipes not showing, or not working? 1.8.9

### ISSUE THREAD

**Issue by Sasikaa** [joekaiser/QuantumFlux#80]
My fresh 1.8.9 modpack put your mod.
My JEI not showing the Quantum RF Entangler, Quantum RF Exciter, Quibit Cell.
Only Clusters, time block, accelerator, ZPE, item magnet.
But, the recipes not showing the ender crystal. This item is showing the item magnet...
Item magnet is not craftable...

Gold casing pictures is PURPLE box...

**Comment by joekaiser** [comment]
Its a beta build and not expected to work properly yet :) I have a habit of uploading a build anytime i make one as there are some people who like to explore them.

Anyway, keep an eye on my twitter. I usually announce when there is a stable build up

**Comment by joekaiser** [comment]
btw, the ender crystal  is a mob drop from enderman now. There won't be a recipe for it

**Comment by Sasikaa** [comment]
OK! The correct info the your mod site please!!!

**Comment by Normal69** [comment]
I have the same problem with latest 1.7.10 version too.
Anything is needed for them? Maybe tin, which isn't in my pack?
