### ISSUE TITLE
[1.8.9] RF Exciter doesn't render correctly

### ISSUE THREAD

**Issue by Okimo** [joekaiser/QuantumFlux#81]
So Quantum Entropy Accelerator has no Gui
Looks like RF Exiter Didn't Recieve any power from RF Entangler ... Or did but don't want to share it with any machine, pipe or Cluster (RF Entagler is draining power)

**Comment by joekaiser** [comment]
Apologies, I haven't had time to update the wiki yet.

The entropy accelerator has no GUI now.
 You feed it items (fuel) with a hopper or pipes. 

I need more information about the exciter...I just ran it in a test lack I have and it is working just fine.

Put down and entangler and push RF into that. The exciters should push RF out to a block that are facing.

I mentioned in my rwddit comment that the exciters need some visual love. If you remember back to 1.7.10 they were small blocks that attached to other blocks. They work the same way, but not visually yet. I'll try to get the render fix out later in the week

**Comment by Okimo** [comment]
So yea it's as you said. 
RF Exiter doesn't work like full block but as Attachment so it was just visual problem.
Btw When is Entagler connected to Quibit Level 5 it does unlimited output?
Because when I connect RF Excitier to Emerald Kinesis Pipe (that has limit of 2560 RF/t) it doesn't push energy to limit of that pipe. Same problem is when i connect Emerald Pipe to Quibit (L5) and let it send power somewhere else. Input seems to be fine.

**Comment by joekaiser** [comment]
entanglers have unlimited output, but an exciter can only do 80/tick. there will be ways to upgrade an entangler

**Comment by Okimo** [comment]
And that Problem with Moving power out of Quibit to pipe?

**Comment by Okimo** [comment]
Also there is one thing I wanted to say ... there is in Blood Magic for 1.8.9 open code to prevent spam in chat. Would be cool to use that :)

**Comment by joekaiser** [comment]
>And that Problem with Moving power out of Quibit to pipe?
What do you mean? you said the input seems to be fine from the L5 to the pipe

**Comment by Okimo** [comment]
Pipe -> Quibit = Fine
Quibit -> Emerald Pipe = Not Fine it doesn't use full speed of that Pipe

**Comment by joekaiser** [comment]
RF Exciter rending fixed in d1f7adc
