### ISSUE TITLE
Port the BattleSuit over from 1.7.10

### ISSUE THREAD

**Issue by joekaiser** [joekaiser/QuantumFlux#84]
The battle suit needs brought over to 1.8.9. 

Don't worry about a recipe at this point. I am not sure what I want for that yet

**Comment by Greg9711** [comment]
When is it going to be readded?
And for the recipe maybe a bit less nether stars to craft it.

**Comment by joekaiser** [comment]
It isn't ported yet. The recipe will be different

**Comment by joekaiser** [comment]
no longer planned
