### ISSUE TITLE
Blocks breaking in 1 punch / exciter power delivery

### ISSUE THREAD

**Issue by Ovadex** [joekaiser/QuantumFlux#86]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* quantumflux-1.8.9-2.0.0

*Mod pack:* custom

*Summary:* Only one exciter is delivering power at a time and blocks are one punch to destroy, no item dropped.

____

####What is happening?
When I place any of the machnie blocks they are destroyed with a single punch and don't drop an item.
Exciters are only delivering power to one machine at a time. Even with multiple entanglers.

####How do you think it should be?
Obv the blocks should take some time to break and drop an item form.
I got the sense from videos you made that the exciters should all deliver power at the same time. 

####How can I reproduce the problem?
Run game, place block, punch it. poof.

**Comment by joekaiser** [comment]
I am working on a fix for the problem of the blocks not dropping. As far as the exciter power delivery problem, make sure you are providing enough power to the network. In all testing I have done, multiple exciters are working. If you are not generating enough power though, it would look like not all are
