### ISSUE TITLE
Cubit Cluster level 2 refuses to output properly

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [joekaiser/QuantumFlux#87]
Submitting a bug report? Please fill out the form below the best you can.

*Version:* 2.0.0

*Mod pack:* Pioneer

*Summary:* The cubit cluster level 2 seems to refuse using its internal buffer to output more than a certain rf/t (A very small amount, around 2/t) andwill not provide machines power.

____

####What is happening? Same as summary

####How do you think it should be? Pretty sure it's supposed to output more than 2 rf/sm, I may be wrong.

####How can I reproduce the problem? Sticking wooden kinesis pipes up to gold kinesis pipes and attempting to power a machine, you'll notice the pipes are pulling VERY little, yet they work fine for neotech energy cells.

**Comment by joekaiser** [comment]
Could maybe be an issue if the RF api has changed recently. On vacation until March 12. I'll look at it as soon as I get back

**Comment by UnstableCodeScarlet** [comment]
Having another issue as well now, the qubit cluster is draining over time with no pipes attached, was that an intentional feature?

**Comment by joekaiser** [comment]
Grab the 2.0.1 version from Curseforge.
