### ISSUE TITLE
Client crashes when RF Exciter is placed

### ISSUE THREAD

**Issue by LordHellscream** [joekaiser/QuantumFlux#89]
I am a noob to RF, but does this mod (using the 1.9 version) compatible with other mods with RF capabilities? I tried to use this with Progressive Automation and it crashed the game everytime I attempted to put a excitor on the PA chopper.

**Comment by joekaiser** [comment]
it *should* be compatible. Considering 1.9 was was released there are bound to be some bugs. I will take a look
