### ISSUE TITLE
QuantumFlux block UI not showing (only display reserve and capacity), also how to get ender crystal?

### ISSUE THREAD

**Issue by LordHellscream** [joekaiser/QuantumFlux#92]
When right click to use generator or quibits, it only show reserve and capacity, the unit is functioning otherwise but machines like entrophy accelerator is not usable without the UI.

In addition, how do you get Ender Crystal? JEI doesn't show the recipe, and when i tried putting ender pearl in a furnance it doesn't do anything. (i was assuming that's what it does).

Please advise.

**Comment by LordHellscream** [comment]
Ok, i removed the CoFHlib and its not crashing anymore, however, when I click to use it, it simply display the reserve in chat, but not showing the inventory (like its seem in your video).

**Comment by joekaiser** [comment]
The block no longer has a GUI. 

Ender crystals are obtained as random drops from enderman. (Not every kill will get you one)
