### ISSUE TITLE
[1.9] 2.0.2 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [joekaiser/QuantumFlux#94]
Issue: quantumflux-1.9-2.0.2 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/46ff87682d4b7bfb6197

fml server latest:
https://gist.github.com/a9a0e8935fe174b49e29

**Comment by joekaiser** [comment]
Thanks, I'll take a lool

**Comment by SDUBZ** [comment]
i got the same error when loading into a new single player world http://pastebin.com/QBcaLNXu

**Comment by joekaiser** [comment]
A fix is being uploaded to curse now. Check there soon
