### ISSUE TITLE
Magnet causes RF items to charge

### ISSUE THREAD

**Issue by mrpcguy** [joekaiser/QuantumFlux#96]
Whenever I have the magnet in my inventory, it will cause flux capacitors, jetpacks, etc. to charge without any actual RF source. It also charges my worn jetpack when turning the magnet on or off. I have tried using those items without having the magnet on me, and they do not charge.

I'm using version 1.3.4 of QuantumFlux for Minecraft 1.7.10.

**Comment by joekaiser** [comment]
The magnet doesn't even know of other item in your inventory. Are you thinking of the Quibit Cell, because that is what is is supposed to do - Assuming you have the power

**Comment by joekaiser** [comment]
Do you still need help, or can I close this?

**Comment by mrpcguy** [comment]
I guess if you can't recreate it, I'll close it myself then.
Oh well..
