### ISSUE TITLE
Adding QF to FTB Unstable mangles TC5 graphics

### ISSUE THREAD

**Issue by charlesbevans** [joekaiser/QuantumFlux#99]
I went to try out QF in FTB Unstable (SSP, Unstable 3.0.42, TC 5.2.4), and the TC5 graphics became corrupted. I've also notified Azanor [TC5 # 595](https://github.com/Azanor/thaumcraft-5/issues/595), as well as another mod author who's mod had the same effect.
![2016-04-25_13 48 27](https://cloud.githubusercontent.com/assets/15851438/14799211/3b4436da-0af0-11e6-9bfa-b1e93854d008.png)

**Comment by joekaiser** [comment]
I am fairty sure this is a graphics issues with the client, not related to any mod. Reload your texture pack (f3+s, i think) and it should fix itself.

**Comment by charlesbevans** [comment]
That worked. Thanks. But, I have to do it every time I load Minecraft. Any ideas on finding the culprit? (I'm using the default texture pack.)

**Comment by joekaiser** [comment]
no :( it happens to me on most packs. I have been told it is a driver issue, but that is all i know

**Comment by charlesbevans** [comment]
Ok. Well, it's a start. Thanks.
